language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-29.0.2
    # The SDK version used to compile your project
    - android-29

before_install:
  - chmod +x gradlew
script:
  - ./gradlew buildCi testCiUnitTestCoverage
after_success:
  - mv app/build/reports/jacoco/testDebugUnitTestCoverage app/build/reports/jacoco/jacocoTestDebugUnitTestReport
  - mv app/build/reports/jacoco/jacocoTestDebugUnitTestReport/testDebugUnitTestCoverage.xml app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml
  - bash <(curl -s https://codecov.io/bash)